name: Create Release

# Create XCFramework when a version is tagged
on:
  push:
    tags:
      - 1.**

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - uses: actions/checkout@v2

      - name: debug
        run: echo data > WireGuardKit.zip && echo 123 > WireGuardKit.sha256

      - uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: WireGuardKit.zip
          bodyFile: WireGuardKit.sha256
