name: Create Release

# Create XCFramework when a version is tagged
on:
  push:
    tags:
      - 1.**

jobs:
  create_release:
    name: Create Release
    runs-on: macos-12
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - uses: actions/checkout@v3

      - name: Build WireGuardKitGo
        run: make wg-go-all

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v2.3.0
        with:
          platforms: ios
          xcconfig: wg-go.xcconfig

      - uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: WireGuardKit.zip
          bodyFile: WireGuardKit.sha256
