name: Create Release

# Create XCFramework when a version is tagged
on:
  push:
    tags:
      - 1.**

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - uses: actions/checkout@v2

      - name: build WireGuardKitGo
        run: cd Sources/WireGuardKitGo && make

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v2.3.0
        with:
          platforms: ios
